encore-full-stack-5/Spring_Boot_CARROT_BE

- src/main/java/com/example/carrot_market/user/controller/UserController.java
- src/main/java/com/example/carrot_market/user/db/UserMapper.java
- src/main/java/com/example/carrot_market/user/dto/UpdateUserRequestDto.java
- src/main/java/com/example/carrot_market/user/service/UserService.java
- src/main/java/com/example/carrot_market/user/service/UserServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/mappers/UsersMapper.xml
> updateUser 개발

- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/repository/ProductMapper.java
- src/main/java/com/example/carrot_market/product/service/ProductService.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/ProductsMapper.xml
> [feat] deleteProduct add

- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/domain/Like.java
- src/main/java/com/example/carrot_market/product/dto/InsertLikeCountRequestDto.java
- src/main/java/com/example/carrot_market/product/repository/ProductMapper.java
- src/main/java/com/example/carrot_market/product/service/ProductService.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/ProductsMapper.xml
> [feat] likeCount

- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/repository/ProductMapper.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/ProductsMapper.xml
> [feat] getProductByUserId add

- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/repository/ProductMapper.java
- src/main/java/com/example/carrot_market/product/service/ProductService.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/ProductsMapper.xml
> [feat] increaseViewCount add

- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/repository/ProductMapper.java
- src/main/java/com/example/carrot_market/product/service/ProductService.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/ProductsMapper.xml
> [feat] refreshProduct add

- src/main/java/com/example/carrot_market/area/db/AreaMapper.java
- src/main/java/com/example/carrot_market/area/service/AreaService.java
- src/main/java/com/example/carrot_market/area/service/AreaServiceImpl.java
- src/main/resources/mappers/AreasMapper.xml
> [feat] getDefaultAreaByUserId add

- src/main/java/com/example/carrot_market/chatting/controller/ChattingController.java
- src/main/java/com/example/carrot_market/chatting/domain/ChatRoomAggregate.java
- src/main/java/com/example/carrot_market/chatting/repository/ChattingMapper.java
- src/main/java/com/example/carrot_market/chatting/service/ChattingService.java
- src/main/java/com/example/carrot_market/chatting/service/ChattingServiceImpl.java
- src/main/java/com/example/carrot_market/core/error/CommonError.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/ChattingMapper.xml
> Feat 채팅목록 변경

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/domain/model/Board.java
- src/main/java/com/example/carrot_market/board/domain/model/Comment.java
- src/main/java/com/example/carrot_market/board/domain/model/NestedComment.java
- src/main/java/com/example/carrot_market/board/dto/AddBoardRequestDto.java
- src/main/java/com/example/carrot_market/board/dto/AddCommentRequestDto.java
- src/main/java/com/example/carrot_market/board/dto/AddNestedCommentRequestDto.java
- src/main/java/com/example/carrot_market/board/dto/UpdateBoardRequestDto.java
- src/main/java/com/example/carrot_market/board/repository/BoardRepository.java
- src/main/java/com/example/carrot_market/board/repository/CommentRepository.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/java/com/example/carrot_market/community/repository/BoardRepository.java
- src/main/java/com/example/carrot_market/community/repository/CommentRepository.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] insertBoard add

- src/main/java/com/example/carrot_market/area/db/AreaMapper.java
- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/domain/ProductAggregate.java
- src/main/java/com/example/carrot_market/product/repository/ImageMapper.java
- src/main/java/com/example/carrot_market/product/repository/ProductMapper.java
- src/main/java/com/example/carrot_market/product/service/ProductService.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/java/com/example/carrot_market/user/db/UserMapper.java
- src/main/resources/mappers/AreasMapper.xml
- src/main/resources/mappers/ImageMapper.xml
- src/main/resources/mappers/ProductsMapper.xml
- src/main/resources/mappers/UsersMapper.xml
> [feat]ProductShow server

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] getBoardListByUserId add

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] getBoardListByAreaId add, [fix] getBoardListByUserId query

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/dto/getDetailBoardResultDto.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] getDetailBoard add

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/dto/UpdateBoardRequestDto.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] updateBoard add

- src/main/java/com/example/carrot_market/area/controller/AreaController.java
- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] deleteBoard add

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/domain/model/Board.java
- src/main/java/com/example/carrot_market/board/domain/model/Comment.java
- src/main/java/com/example/carrot_market/board/dto/AddCommentRequestDto.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] insertComment add

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] selectCommentById add

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] getCommentByBoardId add

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/java/com/example/carrot_market/product/controller/ProductController.java
- src/main/java/com/example/carrot_market/product/service/ProductServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] increaseBoardViewCount add

- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
게시물 삭제 수정
(게시물 삭제 시 해당 게시물에 등록된 댓글도 함께 삭제)
> [fix] deleteBoard

- src/main/java/com/example/carrot_market/board/controller/BoardController.java
- src/main/java/com/example/carrot_market/board/db/BoardMapper.java
- src/main/java/com/example/carrot_market/board/service/BoardService.java
- src/main/java/com/example/carrot_market/board/service/BoardServiceImpl.java
- src/main/resources/mappers/BoarderMapper.xml
> [feat] deleteComment add
